name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@6af3c118c8376c675363897acf1757f7a9be6583
      uses: docker/login-action@v1.13.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        # registry: https://hub.docker.com/repository/docker/webbb/hello
        # Username used to log against the Docker registry
        username: bowenjia@gmail.com
        # Password or personal access token used to log against the Docker registry
        password: 1234567890
        # Specifies whether the given registry is ECR (auto, true or false)
